/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleBootcamp;


import org.apache.commons.lang3.StringUtils;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello World");
        Bye b = new Bye();
        b.display();

        String n="Prateek";
        String n1= StringUtils.upperCase(n);
        System.out.println(n1);

    }
}
